version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://trader:password@db:5432/trading_db
      - REDIS_URL=redis://redis:6379/0
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=trader
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=trading_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6

  celery_worker:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: celery -A tasks worker --loglevel=info

  websocket_server:
    build: .
    ports:
      - "8765:8765"
    command: python mock_server.py

  websocket_client:
    build: .
    depends_on:
      - websocket_server
      - api
      - redis
    environment:
      - DATABASE_URL=postgresql://trader:password@db:5432/trading_db
      - REDIS_URL=redis://redis:6379/0
    command: python client.py

volumes:
  postgres_data: